### ISSUE TITLE
[Suggestion] add an "ETA" (estimated time of arrival) output when the download will be ready

### ISSUE THREAD

**Issue by Wikinaut** [timhutton/twitter-archive-parser#127]
for (example, a snaphsot of my download) 868/15644 media files still downloading.…

… it would be nice to have a **rough estimation** when the download will be ready.

**Comment by lenaschimmel** [comment]
If we want to add a progress bar and/or time estimation, I'd suggest [tqdm](https://github.com/tqdm/tqdm) which is a really impressive piece of software.

On the other hand, it's an additional dependency, and until now, we try to keep the number of dependencies very low. I remember that on another python project, there were a lot of problems because people had different versions of tqdm with a different API, so we would need to watch out for this (in theory, we probably should do the same with the other dependencies, but I guess their API is rather stable?)

**Comment by flauschzelle** [comment]
Fixed in #137 without using tqdm :)
The estimation from tqdm probably wouldn't be more accurate. And adding a dependency that is known as causing compatibility problems, only so that we can have a bit prettier output, does not seem like a good idea.
