### ISSUE TITLE
Bug: tweets with multiple images output with only a single image

### ISSUE THREAD

**Issue by lynnandtonic** [timhutton/twitter-archive-parser#27]
Hi again!

It looks like tweets that have more than one image include only the first image. Is it possible to include them all?

If not no worries! Thank you! 🤩

**Comment by twoscomplement** [comment]
I'd just noticed this as well - I'll share why I've discovered because I don't know if I'll end up getting it into a PR:

I'm looking at [this tweet](https://twitter.com/twoscomplement/status/1581399251673759746) - json for the tweet is in [multi_image.txt](https://github.com/timhutton/twitter-archive-parser/files/9996374/multi_image.txt)

There are four images attached to the tweet.
'full_text' contains a single URL
['entities']['media'] has only a single entry
['extended_entities']['media'] has the details for all four images.

I have some rudimentary code to handle it - but have done no testing to verify that it doesn't break everything else.

My approach is to build a markdown fragment while looping through the entries in ['extended_entities']['media'], and then `body = body.replace(original_url, markdown)` after the loop.

**Comment by timhutton** [comment]
Oh, this sounds like a bug. Thanks for reporting, I'll look into it.
