### ISSUE TITLE
heads-up about DOS line endings

### ISSUE THREAD

**Issue by brainwane** [timhutton/twitter-archive-parser#47]
Thanks for the great tool! Love the friendly command-line explanations and logging.

I'm on Linux. I went to https://raw.githubusercontent.com/timhutton/twitter-archive-parser/main/parser.py and used File: Save in my browser (Firefox) to save the file locally.

When I tried to run it, I got this set of error messages:

~~~
$ python3 -m parser.py
/home/[redacted]/bin/python3: Error while finding module specification for 'parser.py' (ModuleNotFoundError: __path__ attribute not found on 'parser' while trying to find 'parser.py')
$ ./parser.py 
/usr/bin/env: ‘python3\r’: No such file or directory
~~~

and my spouse said -- aha, that file has DOS line-endings. I used my editor (emacs) to change that to Unix-style line endings, saved `parser.py`, and then was able to run it with no problem.

This is not necessarily something you need to fix - just wanted to share this here in case anyone ran into the same error messages and was trying to figure out why. Please feel free to close the issue.

**Comment by timhutton** [comment]
Hi @brainwane. Yes, we had DOS line endings in the repo. That was my fault. (On Windows it's a good idea to do `git config --global core.autocrlf true` but I guess I hadn't on my current git installation.)

I've fixed it now, I think. If you have a moment could you try again what you did before, and see if the issue is fixed?
